### ISSUE TITLE
Building it from scratch and installing the dpkg is not installing lilv properly

### ISSUE THREAD

**Issue by alercunha** [moddevices/lilvlib#4]
After the build and installation finishes there's no lilv.py at /usr/lib/python3/dist-packages/

**Comment by falkTX** [comment]
give me the output of:
dpkg -L python3-lilv

**Comment by alercunha** [comment]
/.
/opt
/opt/mod
/opt/mod/lib
/opt/mod/lib/lv2
/opt/mod/lib/lv2/morph.lv2
/opt/mod/lib/lv2/morph.lv2/morph.h
/opt/mod/lib/lv2/morph.lv2/manifest.ttl
/opt/mod/lib/lv2/morph.lv2/morph.ttl
/opt/mod/lib/lv2/morph.lv2/lv2-morph.doap.ttl
/opt/mod/lib/lv2/schemas.lv2
/opt/mod/lib/lv2/schemas.lv2/rdf.ttl
/opt/mod/lib/lv2/schemas.lv2/rdfs.ttl
/opt/mod/lib/lv2/schemas.lv2/foaf.ttl
/opt/mod/lib/lv2/schemas.lv2/dct.ttl
/opt/mod/lib/lv2/schemas.lv2/dcs.ttl
/opt/mod/lib/lv2/schemas.lv2/manifest.ttl
/opt/mod/lib/lv2/schemas.lv2/doap.ttl
/opt/mod/lib/lv2/schemas.lv2/owl.ttl
/opt/mod/lib/lv2/schemas.lv2/xsd.ttl
/opt/mod/lib/lv2/schemas.lv2/README
/opt/mod/lib/lv2/kx-programs.lv2
/opt/mod/lib/lv2/kx-programs.lv2/programs.h
/opt/mod/lib/lv2/kx-programs.lv2/programs.doap.ttl
/opt/mod/lib/lv2/kx-programs.lv2/manifest.ttl
/opt/mod/lib/lv2/kx-programs.lv2/programs.ttl
/opt/mod/lib/lv2/state.lv2
/opt/mod/lib/lv2/state.lv2/state.ttl
/opt/mod/lib/lv2/state.lv2/manifest.ttl
/opt/mod/lib/lv2/state.lv2/state.h
/opt/mod/lib/lv2/state.lv2/lv2-state.doap.ttl
/opt/mod/lib/lv2/patch.lv2
/opt/mod/lib/lv2/patch.lv2/patch.h
/opt/mod/lib/lv2/patch.lv2/lv2-patch.doap.ttl
/opt/mod/lib/lv2/patch.lv2/manifest.ttl
/opt/mod/lib/lv2/patch.lv2/patch.ttl
/opt/mod/lib/lv2/event.lv2
/opt/mod/lib/lv2/event.lv2/lv2-event.doap.ttl
/opt/mod/lib/lv2/event.lv2/event-helpers.h
/opt/mod/lib/lv2/event.lv2/manifest.ttl
/opt/mod/lib/lv2/event.lv2/event.ttl
/opt/mod/lib/lv2/event.lv2/event.h
/opt/mod/lib/lv2/port-groups.lv2
/opt/mod/lib/lv2/port-groups.lv2/lv2-port-groups.doap.ttl
/opt/mod/lib/lv2/port-groups.lv2/port-groups.h
/opt/mod/lib/lv2/port-groups.lv2/manifest.ttl
/opt/mod/lib/lv2/port-groups.lv2/port-groups.ttl
/opt/mod/lib/lv2/meta
/opt/mod/lib/lv2/meta/meta.ttl
/opt/mod/lib/lv2/meta/manifest.ttl
/opt/mod/lib/lv2/kx-meta
/opt/mod/lib/lv2/kx-meta/meta.ttl
/opt/mod/lib/lv2/kx-meta/manifest.ttl
/opt/mod/lib/lv2/lv2core.lv2
/opt/mod/lib/lv2/lv2core.lv2/lv2core.doap.ttl
/opt/mod/lib/lv2/lv2core.lv2/manifest.ttl
/opt/mod/lib/lv2/lv2core.lv2/lv2.h
/opt/mod/lib/lv2/lv2core.lv2/lv2core.ttl
/opt/mod/lib/lv2/atom.lv2
/opt/mod/lib/lv2/atom.lv2/atom-test.c
/opt/mod/lib/lv2/atom.lv2/atom.h
/opt/mod/lib/lv2/atom.lv2/lv2-atom.doap.ttl
/opt/mod/lib/lv2/atom.lv2/util.h
/opt/mod/lib/lv2/atom.lv2/manifest.ttl
/opt/mod/lib/lv2/atom.lv2/atom.ttl
/opt/mod/lib/lv2/atom.lv2/forge.h
/opt/mod/lib/lv2/instance-access.lv2
/opt/mod/lib/lv2/instance-access.lv2/instance-access.h
/opt/mod/lib/lv2/instance-access.lv2/lv2-instance-access.doap.ttl
/opt/mod/lib/lv2/instance-access.lv2/instance-access.ttl
/opt/mod/lib/lv2/instance-access.lv2/manifest.ttl
/opt/mod/lib/lv2/resize-port.lv2
/opt/mod/lib/lv2/resize-port.lv2/resize-port.ttl
/opt/mod/lib/lv2/resize-port.lv2/lv2-resize-port.doap.ttl
/opt/mod/lib/lv2/resize-port.lv2/resize-port.h
/opt/mod/lib/lv2/resize-port.lv2/manifest.ttl
/opt/mod/lib/lv2/presets.lv2
/opt/mod/lib/lv2/presets.lv2/presets.ttl
/opt/mod/lib/lv2/presets.lv2/presets.h
/opt/mod/lib/lv2/presets.lv2/manifest.ttl
/opt/mod/lib/lv2/presets.lv2/lv2-presets.doap.ttl
/opt/mod/lib/lv2/worker.lv2
/opt/mod/lib/lv2/worker.lv2/manifest.ttl
/opt/mod/lib/lv2/worker.lv2/worker.ttl
/opt/mod/lib/lv2/worker.lv2/worker.h
/opt/mod/lib/lv2/worker.lv2/lv2-worker.doap.ttl
/opt/mod/lib/lv2/uri-map.lv2
/opt/mod/lib/lv2/uri-map.lv2/uri-map.h
/opt/mod/lib/lv2/uri-map.lv2/lv2-uri-map.doap.ttl
/opt/mod/lib/lv2/uri-map.lv2/manifest.ttl
/opt/mod/lib/lv2/uri-map.lv2/uri-map.ttl
/opt/mod/lib/lv2/kx-external-ui.lv2
/opt/mod/lib/lv2/kx-external-ui.lv2/external-ui.h
/opt/mod/lib/lv2/kx-external-ui.lv2/external-ui.doap.ttl
/opt/mod/lib/lv2/kx-external-ui.lv2/manifest.ttl
/opt/mod/lib/lv2/kx-external-ui.lv2/external-ui.ttl
/opt/mod/lib/lv2/parameters.lv2
/opt/mod/lib/lv2/parameters.lv2/lv2-parameters.doap.ttl
/opt/mod/lib/lv2/parameters.lv2/parameters.h
/opt/mod/lib/lv2/parameters.lv2/manifest.ttl
/opt/mod/lib/lv2/parameters.lv2/parameters.ttl
/opt/mod/lib/lv2/mod.lv2
/opt/mod/lib/lv2/mod.lv2/mod.doap.ttl
/opt/mod/lib/lv2/mod.lv2/manifest.ttl
/opt/mod/lib/lv2/mod.lv2/mod.ttl
/opt/mod/lib/lv2/kx-rtmempool.lv2
/opt/mod/lib/lv2/kx-rtmempool.lv2/rtmempool.doap.ttl
/opt/mod/lib/lv2/kx-rtmempool.lv2/manifest.ttl
/opt/mod/lib/lv2/kx-rtmempool.lv2/rtmempool.h
/opt/mod/lib/lv2/kx-rtmempool.lv2/rtmempool.ttl
/opt/mod/lib/lv2/modgui.lv2
/opt/mod/lib/lv2/modgui.lv2/modgui.doap.ttl
/opt/mod/lib/lv2/modgui.lv2/modgui.ttl
/opt/mod/lib/lv2/modgui.lv2/manifest.ttl
/opt/mod/lib/lv2/log.lv2
/opt/mod/lib/lv2/log.lv2/logger.h
/opt/mod/lib/lv2/log.lv2/manifest.ttl
/opt/mod/lib/lv2/log.lv2/log.h
/opt/mod/lib/lv2/log.lv2/log.ttl
/opt/mod/lib/lv2/log.lv2/lv2-log.doap.ttl
/opt/mod/lib/lv2/port-props.lv2
/opt/mod/lib/lv2/port-props.lv2/port-props.h
/opt/mod/lib/lv2/port-props.lv2/port-props.ttl
/opt/mod/lib/lv2/port-props.lv2/lv2-port-props.doap.ttl
/opt/mod/lib/lv2/port-props.lv2/manifest.ttl
/opt/mod/lib/lv2/units.lv2
/opt/mod/lib/lv2/units.lv2/lv2-units.doap.ttl
/opt/mod/lib/lv2/units.lv2/units.h
/opt/mod/lib/lv2/units.lv2/manifest.ttl
/opt/mod/lib/lv2/units.lv2/units.ttl
/opt/mod/lib/lv2/midi.lv2
/opt/mod/lib/lv2/midi.lv2/midi.ttl
/opt/mod/lib/lv2/midi.lv2/lv2-midi.doap.ttl
/opt/mod/lib/lv2/midi.lv2/midi.h
/opt/mod/lib/lv2/midi.lv2/manifest.ttl
/opt/mod/lib/lv2/dynmanifest.lv2
/opt/mod/lib/lv2/dynmanifest.lv2/manifest.ttl
/opt/mod/lib/lv2/dynmanifest.lv2/dynmanifest.ttl
/opt/mod/lib/lv2/dynmanifest.lv2/dynmanifest.h
/opt/mod/lib/lv2/dynmanifest.lv2/lv2-dynmanifest.doap.ttl
/opt/mod/lib/lv2/buf-size.lv2
/opt/mod/lib/lv2/buf-size.lv2/buf-size.ttl
/opt/mod/lib/lv2/buf-size.lv2/manifest.ttl
/opt/mod/lib/lv2/buf-size.lv2/lv2-buf-size.doap.ttl
/opt/mod/lib/lv2/buf-size.lv2/buf-size.h
/opt/mod/lib/lv2/time.lv2
/opt/mod/lib/lv2/time.lv2/time.h
/opt/mod/lib/lv2/time.lv2/lv2-time.doap.ttl
/opt/mod/lib/lv2/time.lv2/manifest.ttl
/opt/mod/lib/lv2/time.lv2/time.ttl
/opt/mod/lib/lv2/options.lv2
/opt/mod/lib/lv2/options.lv2/options.ttl
/opt/mod/lib/lv2/options.lv2/options.h
/opt/mod/lib/lv2/options.lv2/lv2-options.doap.ttl
/opt/mod/lib/lv2/options.lv2/manifest.ttl
/opt/mod/lib/lv2/ui.lv2
/opt/mod/lib/lv2/ui.lv2/ui.h
/opt/mod/lib/lv2/ui.lv2/ui.ttl
/opt/mod/lib/lv2/ui.lv2/manifest.ttl
/opt/mod/lib/lv2/ui.lv2/lv2-ui.doap.ttl
/opt/mod/lib/lv2/data-access.lv2
/opt/mod/lib/lv2/data-access.lv2/data-access.h
/opt/mod/lib/lv2/data-access.lv2/manifest.ttl
/opt/mod/lib/lv2/data-access.lv2/lv2-data-access.doap.ttl
/opt/mod/lib/lv2/data-access.lv2/data-access.ttl
/opt/mod/lib/lv2/urid.lv2
/opt/mod/lib/lv2/urid.lv2/urid.ttl
/opt/mod/lib/lv2/urid.lv2/lv2-urid.doap.ttl
/opt/mod/lib/lv2/urid.lv2/manifest.ttl
/opt/mod/lib/lv2/urid.lv2/urid.h
/opt/mod/bin
/opt/mod/bin/sord_validate
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python3-lilv
/usr/share/doc/python3-lilv/copyright
/usr/share/doc/python3-lilv/changelog.gz
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/_lilv.cpython-34m.so
/usr/bin
/usr/bin/sord_validate_mod

**Comment by falkTX** [comment]
lilv python module is in there, as expected.
/usr/lib/python3/dist-packages/_lilv.cpython-34m.so

maybe you're compiling in a machine and trying to install in a different one?
that does not work, you need to recompile to the target python version.
modules built with python3.4 are not compatible with 3.5 and vice-versa.

**Comment by alercunha** [comment]
I'm compiling and installing in same machine. I have only python 3.4 installed.

Manually copying a lilv.py file to /usr/lib/python3/dist-packages/ fixes the problem.
Without that the following fails:

`python3 -c "import lilv"`
