### ISSUE TITLE
lv2 utils aren't installed via .deb

### ISSUE THREAD

**Issue by unbracketed** [moddevices/lilvlib#7]
Perhaps I've misunderstood, but after getting the `build-python3-lilv.sh` script to run and installing the resulting `.deb` via `dpkg -i`, I don't have any of the lv2* tools available.  I can see in the build output that they are built and supposedly copied into the package file.

**Comment by falkTX** [comment]
The only utility that we want to install with this package is sord_validate, the rest is not important to us.
